### ISSUE TITLE
Scalability vs Memento pattern

### ISSUE THREAD

**Issue by atsepkov** [osartun/Backbone.Undo.js#27]
I apologize for posting an "issue" here, this isn't a bug, just that I couldn't find another way to contact you.

First, thanks for the plugin, it looks like a high quality plugin that you put a lot of effort in. In your overview video, you explain that this plugin doesn't work as well as the memento plugins for large projects. I was hoping you could elaborate on that, what is it about this plugin that limits it compared to Backbone.Memento. I'm trying to figure out which one would work better for me and was leaning towards yours until your comment.

My use case is a version control system for various events that user triggers. So in addition to being able to undo them, I want to let the user reference them later (via some sort of log or diff system I will need to build out - very similar to github commits). The events could stack between days, so with time the system will need to scale. I've looked at memento pattern, and it seems to work by letting the developer define save states, I don't understand why this may be better for large projects than the 3rd solution you mentioned in your video (where you were able to revert the entire drag event, not just the latest coordinate change)?

**Comment by osartun** [comment]
Hi @atsepkov 

thanks for considering using Backbone.Undo.js
I said this, because with the memento pattern you define when and what should be saved as a state in the component itself. You have full control over the savestates.
Backbone.Undo tries to create these savestates automatically from the outside, which works fine for simple apps. For less simple apps it gives you the tools like creating custom undo managers for special models / collections / … and merging these into a main undo manager.

You can probably achieve the same thing with Backbone.Undo as with the memento pattern. But I have the feeling that the more complex an app gets the more difficult it becomes using Backbone.Undo.js.
In the worst case you have a custom undo manager for every model / collection. In this case it would have been easier to just implement the Memento pattern in the first place.

The thing is: In the end this is just my assumption. I developed and used Backbone.Undo.js for an app I created for my Bachelor thesis. I worked a few months on this, but I have no experience with long-term maintenance using Backbone.Undo.js. So, in some regard, this is also kind of a disclaimer. Maybe using Backbone.Undo.js for a large-scale app works out fine. But I don't have the experience with it to guarantee that.

I hope that somehow helps you making a decision.

**Comment by boussou** [comment]
Backbone.undo is not the Memento pattenr, and Backbone.Memento has nothing to do with it. 
To my experience, it works just well, you can control what to undo & and it's perfect.

You may need to "centralize" the undos, and for that you just can use a mixin or use a common parent class. You have to end up implementing something similar to the Redux pattern.

That being said, your use-case is far more complex than just using backbone.undo. I think you are looking for a database feature. Like how CouchDB is implementing it (without compacting db actions).
