### ISSUE TITLE
Publishing v0.2.6 via npm

### ISSUE THREAD

**Issue by chilled-capybara** [osartun/Backbone.Undo.js#32]
The latest version within this repository is [0.2.6](https://github.com/osartun/Backbone.Undo.js/releases/tag/v0.2.6), although the latest version published on `npm` is [`0.2.5`](https://www.npmjs.com/package/backbone-undo?activeTab=versions).

Would it be possible to have a look at this to see if the newer version can be made available.

Thanks

**Comment by ekr3peeK** [comment]
+1, I would be interested in this too.

**Comment by mdk000** [comment]
@osartun any chance to update npm repository with 0.2.6 version?

**Comment by osartun** [comment]
I just published the current state as a new version to npm: https://www.npmjs.com/package/backbone-undo/v/0.2.6

Thanks @mdk000 for mentioning me because it seems like I don't get notified about this repository otherwise?! Because I was unaware that this issue exists (and I also see that there are two PRs open which I didn't know about either). 😬 I haven't been actively maintaining this project in years unfortunately.
